# RFS Framework Documentation
site_name: RFS Framework
site_description: Enterprise-Grade Reactive Functional Serverless Framework for Python
site_author: RFS Framework Team
site_url: https://interactord.github.io/rfs-framework/
repo_name: interactord/rfs-framework
repo_url: https://github.com/interactord/rfs-framework
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 RFS Framework Team

# Theme Configuration
theme:
  name: material
  language: ko
  
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 다크 모드로 전환
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 라이트 모드로 전환
  
  font:
    text: Roboto
    code: Roboto Mono
  
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view

# Plugins
plugins:
  - search:
      lang:
        - en
        - ko
      separator: '[\s\-\.]+'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature_annotations: true
            show_if_no_docstring: false
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
  - mermaid2:
      arguments:
        theme: 'default'
  - awesome-pages
  # - tags:
  #     tags_file: tags.md

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.13.10/dist/mermaid.min.js

# Extra Configuration
extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/interactord/rfs-framework
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/rfs-framework/
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie 동의
    description: >- 
      우리는 쿠키를 사용하여 콘텐츠와 광고를 개인화하고, 소셜 미디어 기능을 제공하며,
      트래픽을 분석합니다. 사이트 사용 정보를 소셜 미디어, 광고 및 분석 파트너와 공유합니다.
    actions:
      - accept
      - reject
      - manage

# Navigation
nav:
  - 홈:
    - index.md
    - 시작하기: getting-started.md
    - 설치 가이드: installation.md
    - 변경 이력: changelog.md
  
  - 핵심 개념:
    - 01-core-patterns.md
    - 02-dependency-injection.md
    - 03-configuration.md
    - 04-transactions.md
    - 16-hot-library.md
    - Readable HOF: 19-readable-hof-guide.md
    - MonoResult/FluxResult: 20-monoresult-guide.md
    - FastAPI 통합: 21-fastapi-integration.md
    - 모니터링: 22-monitoring-observability.md
    - 테스팅: 23-testing-guide.md
    - 16-event-system.md
    - 17-profiles.md
    - 17-state-machine.md
    - 18-database.md
  
  - 프로덕션:
    - 05-deployment.md
    - 06-rollback.md
    - 07-logging.md
    - 08-monitoring.md
    - 09-validation.md
  
  - 보안:
    - 10-access-control.md
    - 11-security.md
  
  - 고급 기능:
    - 12-circuit-breaker.md
    - 13-load-balancing.md
    - 14-cli-interface.md
    - 15-code-quality.md
  
  - API 레퍼런스:
    - API 개요: api/index.md
    - Core:
      - Result Pattern: api/core/result.md
      - Configuration: api/core/config.md
      - Registry: api/core/registry.md
      - Annotations: core/annotations.md
    - Reactive:
      - Mono: api/reactive/mono.md
      - Flux: api/reactive/flux.md
      - MonoResult: api/reactive/mono-result.md
      - FluxResult: api/reactive/flux-result.md
    - HOF:
      - Core Functions: api/hof/core.md
      - Collections: api/hof/collections.md
      - Monads: api/hof/monads.md
      - Readable HOF: api/hof/readable.md
  
  - 가이드:
    - 사용자 가이드: USER_GUIDE.md
    - API 레퍼런스: API_REFERENCE.md
    - 릴리스 노트: RELEASE_NOTES.md
    - 마이그레이션: MIGRATION_GUIDE.md
  
  - 예제:
    - Readable HOF:
      - 보안 감사 시스템: examples/readable-hof/security-audit.md
      - 데이터 파이프라인 모니터링: examples/readable-hof/data-pipeline.md
      - 설정 검증 시스템: examples/readable-hof/config-validation.md
  
  - 프로젝트:
    - 기여 가이드: CONTRIBUTING.md
    - 구현 현황: 99-implementation-status.md
    - TODO: TODO.md
    - 태그: tags.md
    - 라이선스: LICENSE.md